-- HarvestHome Listing Performance V10
-- Run this ONCE in Supabase SQL Editor.
-- Safe to run again.

-- 1) Make sure listings have a view counter.
alter table public.listings
  add column if not exists views integer not null default 0;

-- 2) Store listing-view events.
create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  viewer_id uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create index if not exists listing_views_listing_idx
  on public.listing_views(listing_id, viewed_at desc);

create index if not exists listing_views_viewer_idx
  on public.listing_views(viewer_id, listing_id, viewed_at desc);

alter table public.listing_views enable row level security;

drop policy if exists "listing owners can view listing view events" on public.listing_views;
create policy "listing owners can view listing view events"
on public.listing_views for select
to authenticated
using (
  exists (
    select 1 from public.listings l
    where l.id = listing_views.listing_id
      and l.seller_id = auth.uid()
  )
);

-- 3) Record a public listing view securely.
create or replace function public.record_listing_view(
  p_listing_id uuid
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_views integer;
begin
  if auth.uid() is null then
    raise exception 'You must be logged in';
  end if;

  if not exists (
    select 1
    from public.listings
    where id = p_listing_id
      and status = 'approved'
  ) then
    return 0;
  end if;

  -- A seller's own browsing does not inflate public view counts.
  if exists (
    select 1
    from public.listings
    where id = p_listing_id
      and seller_id = auth.uid()
  ) then
    select coalesce(views, 0) into v_views
    from public.listings
    where id = p_listing_id;
    return coalesce(v_views, 0);
  end if;

  insert into public.listing_views(listing_id, viewer_id)
  values(p_listing_id, auth.uid());

  update public.listings
  set views = coalesce(views, 0) + 1
  where id = p_listing_id
    and status = 'approved'
  returning views into v_views;

  return coalesce(v_views, 0);
end;
$$;

grant execute on function public.record_listing_view(uuid) to authenticated;

-- 4) Return per-listing seller analytics without exposing buyer identities.
create or replace function public.get_seller_listing_performance(
  p_seller_id uuid
)
returns table (
  id uuid,
  title text,
  country text,
  location text,
  status text,
  views integer,
  conversations bigint,
  unique_buyers bigint,
  recommendations bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or auth.uid() <> p_seller_id then
    raise exception 'Not allowed';
  end if;

  return query
  select
    l.id,
    l.title,
    l.country,
    l.location,
    l.status,
    coalesce(l.views, 0)::integer as views,
    (
      select count(*)
      from public.conversations c
      where c.listing_id = l.id
    )::bigint as conversations,
    (
      select count(distinct c.buyer_id)
      from public.conversations c
      where c.listing_id = l.id
    )::bigint as unique_buyers,
    (
      select count(*)
      from public.seller_recommendations sr
      where sr.listing_id = l.id
        and sr.seller_id = l.seller_id
    )::bigint as recommendations
  from public.listings l
  where l.seller_id = p_seller_id
    and l.status <> 'deleted'
  order by l.created_at desc nulls last;
end;
$$;

grant execute on function public.get_seller_listing_performance(uuid) to authenticated;
