(() => {
"use strict";
const C = window.HARVESTHOME_CONFIG || { APP_NAME:"HarvestHome", VERSION:"V8", SUPPORTED_COUNTRIES:[{name:"Nigeria",code:"NG",currency:"NGN",symbol:"₦"}], CATEGORIES:["All categories","Houses","Land","Equipment","Farm Produce"], MODES:["All","Sale","Lease"], LOCATIONS:{Nigeria:["All locations"]}, DEFAULT_COUNTRY:"Nigeria", DEFAULT_CURRENCY:"NGN", MAX_IMAGE_FILES:6, MAX_VIDEO_MB:25 };
const sb = (window.supabase && C.SUPABASE_URL && C.SUPABASE_ANON_KEY && C.SUPABASE_URL.startsWith("http")) ? window.supabase.createClient(C.SUPABASE_URL, C.SUPABASE_ANON_KEY) : null;
let authUser = null, authProfile = null;
const KEYS = {users:"hh_v4_users",session:"hh_v4_session",favourites:"hh_v4_favourites",enquiries:"hh_v4_enquiries",sellerListings:"hh_v4_seller_listings",country:"hh_v4_country",currency:"hh_v4_currency",reset:"hh_v6_reset_tokens",payments:"hh_v6_payments",notifications:"hh_v8_notifications"};
const DEMO_ADMIN={email:"admin@harvesthome.app",name:"HarvestHome Admin",password:"Admin123!",role:"Admin"};
const V5 = {maxImages:6,maxVideoMB:25};
const mapURL=l=>`https://www.openstreetmap.org/search?query=${encodeURIComponent(`${l.location||""}, ${l.country||""}`)}`;
const readFiles=files=>Promise.all([...files].map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({name:file.name,type:file.type,data:r.result});r.onerror=reject;r.readAsDataURL(file)})));

const seed = [];

const state={view:"marketplace",search:"",country:localStorage.getItem(KEYS.country)||C.DEFAULT_COUNTRY,location:"All locations",category:"All categories",mode:"All",dashboardTab:"overview",authMode:"login"};
let chatTimer=null;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const json=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const users=()=>{let us=json(KEYS.users,[]);if(!us.some(u=>u.email===DEMO_ADMIN.email)){us.push({...DEMO_ADMIN});put(KEYS.users,us)}return us};
const session=()=>json(KEYS.session,null);
const user=()=> authUser ? ({...authUser,...(authProfile||{}), email:authUser.email, id:authUser.id, name:(authProfile&&authProfile.full_name)||authUser.user_metadata?.full_name||authUser.email, role:(authProfile&&authProfile.role)||authUser.user_metadata?.role||"Buyer"}) : (session()?users().find(u=>u.email===session().email):null);
const countryInfo=()=>C.SUPPORTED_COUNTRIES.find(x=>x.name===state.country)||C.SUPPORTED_COUNTRIES[0];
const listings=()=>json(KEYS.sellerListings,[]).filter(l=>l&&l.seller_id&&l.status!=="deleted");
async function syncListings(){
  if(!sb)return;
  try{
    const {data,error}=await sb.from('listings').select('*, profiles: seller_id(full_name)').order('created_at',{ascending:false});
    if(error)throw error;
    const remote=(data||[]).filter(l=>l.seller_id&&l.status!=="deleted").map(l=>({...l,id:l.id,ownerEmail:authUser?.id===l.seller_id?(authUser.email||''):undefined,seller:l.profiles?.full_name||'HarvestHome Seller',images:l.cover_url?[{data:l.cover_url}]:[],video:l.video_url?{data:l.video_url}:null,views:l.views||0}));
    put(KEYS.sellerListings,remote);
  }catch(e){console.warn('Supabase listings sync failed',e.message)}
}

async function fav(id){
  const u=user();
  if(!u||!authUser){auth("login");toast("Log in to save a favourite.",true);return}
  if(!sb){toast("Favourites are unavailable right now.",true);return}
  try{
    const f=json(KEYS.favourites,{});
    const current=f[u.email]||[];
    if(current.includes(id)){
      const {error}=await sb.from('favourites').delete().eq('user_id',authUser.id).eq('listing_id',id);
      if(error)throw error;
      f[u.email]=current.filter(x=>x!==id);
      toast("Removed from favourites.");
    }else{
      const {error}=await sb.from('favourites').insert({user_id:authUser.id,listing_id:id});
      if(error)throw error;
      f[u.email]=[...current,id];
      toast("Saved to favourites.");
    }
    put(KEYS.favourites,f);
    render();
  }catch(e){toast(e.message||"Favourite could not be saved.",true)}
}

function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function money(n,cur){try{return new Intl.NumberFormat("en",{style:"currency",currency:cur,maximumFractionDigits:0}).format(Number(n))}catch{return `${cur} ${n}`}}
function slug(v){return String(v).toLowerCase().replace(/\s+/g,"-")}
function toast(m,error=false){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";document.body.append(t)}t.textContent=m;t.className="toast "+(error?"error ":"");requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>t.classList.remove("show"),2800)}
function options(a,s){return a.map(x=>`<option ${x===s?"selected":""}>${esc(x)}</option>`).join("")}

function render(){document.body.innerHTML=`<div id="app">${state.view==="marketplace"?marketplace():dashboard()}</div><div id="modalRoot"></div><div id="toast"></div>`;bind()}
async function createNotification(userId,type,title,message,listingId=null){if(!sb||!userId)return;try{const {error}=await sb.from('notifications').insert({user_id:userId,type,title,message,listing_id:listingId});if(error)throw error}catch(e){console.warn('Notification could not be created:',e.message)}}
async function syncNotifications(){if(!sb||!authUser)return;try{const {data,error}=await sb.from('notifications').select('*').eq('user_id',authUser.id).order('created_at',{ascending:false});if(error)throw error;const n=json(KEYS.notifications,{});n[authUser.id]=data||[];put(KEYS.notifications,n)}catch(e){console.warn('Supabase notifications sync failed',e.message)}}
async function uploadProfilePhoto(file){if(!sb||!authUser){toast('Please log in first.',true);return}if(!file)return;if(!file.type.startsWith('image/')){toast('Please choose an image file.',true);return}if(file.size>5*1024*1024){toast('Profile photo must be 5 MB or smaller.',true);return}try{const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'jpg';const path=authUser.id+'/avatar.'+ext;const up=await sb.storage.from('profile-media').upload(path,file,{upsert:true,contentType:file.type});if(up.error)throw up.error;const url=sb.storage.from('profile-media').getPublicUrl(path).data.publicUrl+'?v='+Date.now();const {error}=await sb.from('profiles').update({avatar_url:url,updated_at:new Date().toISOString()}).eq('id',authUser.id);if(error)throw error;await loadProfile();render();toast('Profile photo updated.')}catch(e){toast(e.message||'Profile photo could not be uploaded.',true)}}
async function markNotificationRead(id){if(!sb||!authUser)return;try{const {error}=await sb.from('notifications').update({is_read:true}).eq('id',id).eq('user_id',authUser.id);if(error)throw error;await syncNotifications();render()}catch(e){toast(e.message||'Notification could not be updated.',true)}}
async function markAllNotificationsRead(){if(!sb||!authUser)return;try{const {error}=await sb.from('notifications').update({is_read:true}).eq('user_id',authUser.id).eq('is_read',false);if(error)throw error;await syncNotifications();render();toast('All notifications marked as read.')}catch(e){toast(e.message||'Notifications could not be updated.',true)}}
async function syncFavourites(){
  if(!sb||!authUser)return;
  try{
    const {data,error}=await sb.from('favourites').select('listing_id').eq('user_id',authUser.id);
    if(error)throw error;
    const f=json(KEYS.favourites,{});
    f[authUser.email]=(data||[]).map(x=>x.listing_id);
    put(KEYS.favourites,f);
  }catch(e){console.warn('Supabase favourites sync failed',e.message)}
}
async function loadProfile(){if(!sb||!authUser){authProfile=null;return}const {data}=await sb.from('profiles').select('*').eq('id',authUser.id).maybeSingle();authProfile=data||null}
async function loadAuth(){if(!sb){render();return}const {data}=await sb.auth.getSession();authUser=data.session?.user||null;await loadProfile();await syncListings();await syncFavourites();await syncNotifications();render();}
function header(){let u=user();return `<header class="site-header"><div class="container nav-wrap"><button class="brand" data-a="home"><span class="brand-mark">🌿</span><span><strong>HarvestHome</strong><small>International marketplace</small></span></button><nav class="desktop-nav"><button data-a="home">Marketplace</button><button data-scroll="categories">Categories</button><button data-scroll="how">How it works</button></nav><div class="nav-actions"><select id="countryTop" aria-label="Country">${options(C.SUPPORTED_COUNTRIES.map(x=>x.name),state.country)}</select>${u?`<button class="ghost-btn account-btn" data-a="dashboard">${u.avatar_url?`<img class="nav-avatar" src="${esc(u.avatar_url)}" alt="">`:``}My account</button>${(u.role==="Admin"||u.role==="Moderator")?`<button class="ghost-btn" data-a="admin">Moderation</button>`:""}<button class="primary-btn small" data-a="logout">Logout</button>`:`<button class="ghost-btn" data-a="login">Login</button><button class="primary-btn small" data-a="signup">Join</button>`}</div></div></header>`}
function marketplace(){let ls=filtered();return `${header()}<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">🌍 Global marketplace</span><h1>Buy, sell & lease <span>what matters.</span></h1><p>Discover houses, land, equipment and farm produce across markets around the world.</p><div class="hero-search"><input id="searchInput" value="${esc(state.search)}" placeholder="Search property, land, tractors, produce..."><button class="primary-btn" data-a="search">Search</button></div><div class="quick-stats"><span><b>${C.SUPPORTED_COUNTRIES.length}</b> launch markets</span><span><b>7+</b> categories</span><span><b>1</b> global platform</span></div></div><div class="hero-card"><div class="hero-card-icon">🌎</div><h3>One marketplace. Many markets.</h3><p>Start in Nigeria and discover opportunities across international markets.</p><button class="outline-btn" data-scroll="categories">Browse categories →</button></div></div></section>
<section class="filters-section"><div class="container filter-bar"><select id="countryFilter">${options(C.SUPPORTED_COUNTRIES.map(x=>x.name),state.country)}</select><select id="locationFilter">${options(C.LOCATIONS[state.country]||["All locations"],state.location)}</select><select id="categoryFilter">${options(C.CATEGORIES,state.category)}</select><select id="modeFilter">${options(C.MODES,state.mode)}</select><button class="clear-btn" data-a="clear">Clear</button></div></section>
<section class="section" id="categories"><div class="container"><div class="section-heading"><div><span class="eyebrow">Explore</span><h2>Browse categories</h2></div><span class="result-count">${ls.length} results in ${esc(state.country)}</span></div><div class="category-grid">${cat("🏠","Houses","Homes, apartments & property","Houses")}${cat("🌍","Land","Residential & agricultural land","Land")}${cat("🚜","Equipment","Tractors, machinery & tools","Equipment")}${cat("🌾","Farm Produce","Crops & fresh produce","Farm Produce")}</div></div></section>
<section class="section listings-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">Marketplace</span><h2>Featured listings</h2></div><span class="result-count">${ls.length} available</span></div><div class="listing-grid">${ls.map(card).join("")||empty()}</div></div></section>
<section class="country-strip"><div class="container"><span class="eyebrow">Explore markets</span><h2>HarvestHome around the world</h2><div class="country-grid">${C.SUPPORTED_COUNTRIES.map(x=>`<button data-country="${esc(x.name)}"><b>${flag(x.code)}</b><span>${esc(x.name)}</span><small>${esc(x.currency)} · ${esc(x.symbol)}</small></button>`).join("")}</div></div></section>
<section class="trust-section" id="how"><div class="container trust-grid"><div><span class="eyebrow">Built to scale</span><h2>One trusted marketplace for local and international opportunities.</h2><p>HarvestHome keeps the same simple experience while making countries, currencies and locations part of the marketplace from the start.</p></div><div class="trust-items"><div><span>✓</span><b>Multi-country search</b><small>Switch markets without leaving HarvestHome.</small></div><div><span>✓</span><b>Multi-currency listings</b><small>Display prices in the currency of each market.</small></div><div><span>✓</span><b>Local account tools</b><small>Buyers and sellers can manage activity from one account.</small></div></div></div></section>${footer()}`}
function cat(i,t,d,v){return `<button class="category-card" data-cat="${esc(v)}"><span>${i}</span><div><h3>${t}</h3><p>${d}</p></div><b>→</b></button>`}
function flag(c){return ({NG:"🇳🇬",GH:"🇬🇭",KE:"🇰🇪",ZA:"🇿🇦",GB:"🇬🇧",US:"🇺🇸",CA:"🇨🇦",AE:"🇦🇪"}[c]||"🌍")}
function filtered(){let q=state.search.toLowerCase().trim();return listings().filter(l=>(l.status||"approved")==="approved"&&(l.country||"Nigeria")===state.country&&(!q||`${l.title} ${l.category} ${l.location} ${l.description} ${l.seller}`.toLowerCase().includes(q))&&(state.location==="All locations"||l.location===state.location)&&(state.category==="All categories"||l.category===state.category)&&(state.mode==="All"||l.mode===state.mode))}
function card(l){let u=user(),f=json(KEYS.favourites,{}),fav=u&&(f[u.email]||[]).includes(l.id);let img=l.images&&l.images[0]&&l.images[0].data;return `<article class="listing-card"><div class="listing-image ${slug(l.category)}">${img?`<img src="${img}" alt="${esc(l.title)}">`:`<span>${l.emoji||"📦"}</span>`}<button class="heart ${fav?"active":""}" data-fav="${l.id}">${fav?"♥":"♡"}</button><span class="mode-pill">${esc(l.mode)}</span></div><div class="listing-body"><span class="listing-category">${esc(l.category)}</span><h3>${esc(l.title)}</h3><p class="location">📍 ${esc(l.location)} · ${esc(l.country)}</p><p class="description">${esc(l.description)}</p><div class="listing-bottom"><strong>${money(l.price,l.currency||countryInfo().currency)}</strong><span>${l.views||0} views</span></div><div class="listing-actions"><button class="outline-btn full" data-contact="${l.id}">Contact seller</button><div class="media-links"><a target="_blank" rel="noopener" href="${mapURL(l)}">📍 Map</a>${l.video?`<span>🎥 Video</span>`:""}</div></div></div></article>`}
function empty(){return `<div class="empty-state"><div>🔎</div><h3>No matching listings</h3><p>Try another market, location or search.</p><button class="primary-btn" data-a="clear">Clear filters</button></div>`}
function footer(){return `<footer><div class="container footer-grid"><div><div class="footer-brand">🌿 HarvestHome</div><p>The international marketplace for property, equipment and farm produce.</p></div><div><b>Markets</b>${C.SUPPORTED_COUNTRIES.slice(0,4).map(x=>`<button data-country="${esc(x.name)}">${flag(x.code)} ${esc(x.name)}</button>`).join("")}</div><div><b>Account</b><button data-a="login">Login</button><button data-a="signup">Create account</button></div></div><div class="container footer-bottom">© ${new Date().getFullYear()} HarvestHome · International marketplace</div></footer>`}

function adminPanel(){if(!user()||!['Admin','Moderator'].includes(user().role))return `<div class="empty-state"><h3>Access denied</h3></div>`;let ls=json(KEYS.sellerListings,[]);return `<div class="panel-heading"><div><span class="eyebrow">Admin workspace</span><h2>Moderation center</h2></div><span class="result-count">${ls.length} seller listings</span></div><div class="table-wrap"><table><thead><tr><th>Listing</th><th>Seller</th><th>Status</th><th>Action</th></tr></thead><tbody>${ls.length?ls.map(l=>`<tr><td><b>${esc(l.title)}</b><small>${esc(l.country)} · ${esc(l.location)}</small></td><td>${esc(l.seller||l.ownerEmail||'')}</td><td><span class="status-pill ${slug(l.status||'approved')}">${esc(l.status||'approved')}</span></td><td><button class="ghost-btn" data-mod="approve:${l.id}">Approve</button> <button class="ghost-btn" data-mod="reject:${l.id}">Reject</button> <button class="danger-text" data-mod="delete:${l.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4">No seller listings to moderate.</td></tr>`}</tbody></table></div><div class="dashboard-callout"><b>Admin roles</b><p>Admin and Moderator accounts can review seller listings. The included demo admin is for testing only; change it before production.</p></div>`}
function dashboard(){let u=user();if(!u){state.view="marketplace";return marketplace()}let favs=json(KEYS.favourites,{})[u.email]||[], mine=json(KEYS.sellerListings,[]).filter(x=>authUser&&String(x.seller_id)===String(authUser.id)), enq=json(KEYS.enquiries,[]).filter(x=>x.buyerEmail===u.email), notifications=authUser?(json(KEYS.notifications,{})[authUser.id]||[]):[], unread=notifications.filter(n=>!n.is_read).length;return `${header()}<section class="dashboard-hero"><div class="container"><button class="back-btn" data-a="home">← Marketplace</button><span class="eyebrow">My account</span><h1>Welcome, ${esc(u.name.split(" ")[0])}.</h1><p>Manage your favourites, enquiries and seller listings across your selected market.</p></div></section><section class="dashboard-section"><div class="container dashboard-layout"><aside class="dashboard-nav"><button class="${state.dashboardTab==="overview"?"active":""}" data-tab="overview">Overview</button><button class="${state.dashboardTab==="favourites"?"active":""}" data-tab="favourites">Favourites (${favs.length})</button><button class="${state.dashboardTab==="listings"?"active":""}" data-tab="listings">My listings (${mine.length})</button><button class="${state.dashboardTab==="notifications"?"active":""}" data-tab="notifications">🔔 Notifications${unread?` (${unread})`:``}</button><button class="${state.dashboardTab==="enquiries"?"active":""}" data-tab="enquiries">Enquiries (${enq.length})</button><button class="${state.dashboardTab==="chats"?"active":""}" data-tab="chats">💬 Chats</button>${(u.role==="Admin"||u.role==="Moderator")?`<button class="${state.dashboardTab==="moderation"?"active":""}" data-tab="moderation">Moderation</button>`:""}<button class="${state.dashboardTab==="payments"?"active":""}" data-tab="payments">Payments</button><button data-a="logout">Logout</button></aside><div class="dashboard-content">${dashTab(u,favs,mine,enq)}</div></div></section>${footer()}`}
function dashTab(u,favs,mine,enq){
if(state.dashboardTab==="notifications"){let ns=authUser?(json(KEYS.notifications,{})[authUser.id]||[]):[];return `<div class="panel-heading"><div><span class="eyebrow">Updates</span><h2>Notifications</h2></div>${ns.some(n=>!n.is_read)?'<button class="outline-btn" data-a="markAllNotifications">Mark all as read</button>':''}</div>${ns.length?'<div class="notification-list">'+ns.map(n=>`<button class="notification-item ${n.is_read?'read':'unread'}" data-notification="${esc(n.id)}"><span class="notification-icon">${n.type==='listing_review'?'📋':'🔔'}</span><span><b>${esc(n.title)}</b><p>${esc(n.message)}</p><small>${new Date(n.created_at).toLocaleString()}</small></span></button>`).join('')+'</div>':'<div class="empty-state compact"><div>🔔</div><h3>No notifications</h3><p>You will see listing review and account updates here.</p></div>'}`}
if(state.dashboardTab==="favourites"){let ls=listings().filter(x=>favs.includes(x.id));return `<div class="panel-heading"><div><span class="eyebrow">Saved</span><h2>Your favourites</h2></div></div>${ls.length?`<div class="listing-grid">${ls.map(card).join("")}</div>`:`<div class="empty-state compact"><div>♡</div><h3>No favourites yet</h3><p>Save listings from any market.</p></div>`} `}
if(state.dashboardTab==="listings")return `<div class="panel-heading"><div><span class="eyebrow">Seller workspace</span><h2>My listings</h2></div><button class="primary-btn" data-a="newListing">+ Create listing</button></div>${mine.length?`<div class="table-wrap"><table><thead><tr><th>Listing</th><th>Market</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody>${mine.map(l=>`<tr><td><b>${esc(l.title)}</b></td><td>${esc(l.country)} · ${esc(l.location)}</td><td>${money(l.price,l.currency)}</td><td><span class="status-pill ${slug(l.status||'pending')}">${l.status==='pending'?'Under review':l.status==='approved'?'Approved':l.status==='rejected'?'Not approved':esc(l.status||'')}</span></td><td><button class="danger-text" data-del="${l.id}">Delete</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state compact"><div>＋</div><h3>No listings yet</h3><button class="primary-btn" data-a="newListing">Create listing</button></div>`}`;
if(state.dashboardTab==="payments")return `<div class="panel-heading"><div><span class="eyebrow">Billing</span><h2>Payments</h2></div><button class="primary-btn" data-a="pay">Make a payment</button></div><div class="dashboard-callout"><b>Paystack checkout</b><p>Pay for featured listings, verification or seller plans through secure server-side initialization.</p><button class="primary-btn" data-a="pay">Continue to payment</button></div>`;
if(state.dashboardTab==="moderation")return adminPanel();
if(state.dashboardTab==="enquiries")return `<div class="panel-heading"><div><span class="eyebrow">Messages</span><h2>My enquiries</h2></div></div>${enq.length?enq.map(e=>`<div class="enquiry"><div><b>${esc(e.listingTitle)}</b><p>${esc(e.message)}</p></div><small>${esc(e.date)}</small></div>`).join(""):`<div class="empty-state compact"><div>💬</div><h3>No enquiries yet</h3></div>`}`;
return `<div class="panel-heading"><div><span class="eyebrow">Account overview</span><h2>Your global workspace</h2></div></div><div class="stat-grid"><div class="stat"><span>Favourites</span><strong>${favs.length}</strong></div><div class="stat"><span>My listings</span><strong>${mine.length}</strong></div><div class="stat"><span>Enquiries</span><strong>${enq.length}</strong></div></div><div class="account-card"><div class="avatar-wrap">${u.avatar_url?`<img class="profile-avatar" src="${esc(u.avatar_url)}" alt="Profile photo">`:`<div class="avatar">${esc(u.name.charAt(0).toUpperCase())}</div>`}<label class="outline-btn photo-btn">📷 ${u.avatar_url?"Change photo":"Add profile photo"}<input id="profilePhotoInput" type="file" accept="image/*" hidden></label></div><div><h3>${esc(u.name)}</h3><p>${esc(u.email)}</p><small>${esc(u.role||"Buyer")} account</small><p class="profile-help">Your profile photo is visible on your account and can help buyers and sellers recognize who they are dealing with.</p></div></div><div class="dashboard-callout"><b>Ready to sell internationally?</b><p>Create a listing and choose its country, location and currency.</p><button class="primary-btn" data-a="newListing">Create listing</button></div>`}

async function getChatConversations(){
  if(!sb||!authUser)return [];
  const {data,error}=await sb.from('conversations').select('*').or(`buyer_id.eq.${authUser.id},seller_id.eq.${authUser.id}`).order('updated_at',{ascending:false});
  if(error)throw error;
  return data||[];
}
function chatTab(u){if(!sb||!authUser)return `<div class="empty-state compact"><div>💬</div><h3>Chat is unavailable</h3><p>Connect your Supabase project to use buyer-seller chat.</p></div>`;setTimeout(loadChatsPanel,0);return `<div class="panel-heading"><div><span class="eyebrow">Buyer ↔ Seller</span><h2>Your chats</h2></div></div><div id="chatListPanel"><div class="empty-state compact"><div>⏳</div><h3>Loading chats…</h3></div></div>`}
async function loadChatsPanel(){const root=$("#chatListPanel");if(!root||!sb||!authUser)return;try{const cs=await getChatConversations();if(!cs.length){root.innerHTML=`<div class="empty-state compact"><div>💬</div><h3>No chats yet</h3><p>Open an approved listing and tap Contact seller to start a private conversation.</p></div>`;return}const ids=cs.map(c=>c.listing_id).filter(Boolean);const {data:ls,error}=await sb.from('listings').select('id,title,location,country,seller_id').in('id',ids);if(error)throw error;const map=Object.fromEntries((ls||[]).map(x=>[x.id,x]));root.innerHTML=`<div class="chat-list">${cs.map(c=>{const l=map[c.listing_id]||{};const other=c.buyer_id===authUser.id?"Seller":"Buyer";return `<button class="chat-row" data-chat="${esc(c.id)}" data-listing="${esc(c.listing_id||"")}"><span class="chat-avatar">💬</span><span><b>${esc(l.title||"HarvestHome listing")}</b><small>${esc(other)} · ${esc(l.location||"")}, ${esc(l.country||"")}</small></span><span class="chat-arrow">→</span></button>`}).join("")}</div>`;$$("[data-chat]",root).forEach(e=>e.onclick=async()=>{const l=listings().find(x=>String(x.id)===String(e.dataset.listing));if(l)await openChat(e.dataset.chat,l)})}catch(e){root.innerHTML=`<div class="empty-state compact"><div>⚠️</div><h3>Chats could not be loaded</h3><p>${esc(e.message||"Please try again.")}</p></div>`}}
async function contact(id){const u=user();if(!u){auth("login");toast("Log in to contact the seller.",true);return}const l=listings().find(x=>String(x.id)===String(id));if(!l){toast("Listing not found.",true);return}if(!sb||!authUser||!l.seller_id){toast("This listing is not connected to a seller account yet.",true);return}if(l.seller_id===authUser.id){toast("You cannot contact yourself about your own listing.",true);return}try{let {data:c,error}=await sb.from('conversations').select('*').eq('listing_id',l.id).eq('buyer_id',authUser.id).eq('seller_id',l.seller_id).maybeSingle();if(error)throw error;if(!c){const r=await sb.from('conversations').insert({listing_id:l.id,buyer_id:authUser.id,seller_id:l.seller_id}).select().single();if(r.error)throw r.error;c=r.data}openChat(c.id,l)}catch(e){toast(e.message||"Could not start the chat.",true)}}
async function openChat(conversationId,listing){clearInterval(chatTimer);await renderChatModal(conversationId,listing);chatTimer=setInterval(()=>renderChatModal(conversationId,listing,true),5000)}
async function renderChatModal(conversationId,listing,silent=false){if(!sb||!authUser)return;try{const {data:msgs,error}=await sb.from('messages').select('id,sender_id,body,created_at').eq('conversation_id',conversationId).order('created_at',{ascending:true});if(error)throw error;if(!silent)$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal wide chat-modal"><button class="modal-close" data-chat-close>×</button><span class="eyebrow">Private buyer ↔ seller chat</span><h2>${esc(listing?.title||"HarvestHome listing")}</h2><div id="chatMessages" class="chat-messages"></div><form id="chatForm" class="chat-form"><textarea name="message" rows="2" maxlength="2000" placeholder="Write a message to the seller…" required></textarea><button class="primary-btn">Send message</button></form><small class="demo-note">Messages are stored securely in Supabase and only the buyer and seller can access this conversation.</small></div></div>`;const box=$("#chatMessages");if(!box)return;box.innerHTML=(msgs||[]).map(m=>`<div class="chat-bubble ${m.sender_id===authUser.id?"mine":"theirs"}"><p>${esc(m.body)}</p><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join("")||'<div class="chat-empty">Start the conversation with the seller.</div>';box.scrollTop=box.scrollHeight;if(!silent){$("[data-chat-close]")?.addEventListener("click",()=>{clearInterval(chatTimer);chatTimer=null;close()});$("#chatForm")?.addEventListener("submit",e=>sendChatMessage(e,conversationId,listing))}}catch(e){if(!silent)toast(e.message||"Could not load chat.",true)}}
async function sendChatMessage(e,conversationId,listing){
  e.preventDefault();
  const message=String(new FormData(e.target).get('message')||"").trim();
  if(!message||!sb||!authUser)return;
  try{
    const {data:conversation,error:conversationError}=await sb.from('conversations').select('id,buyer_id,seller_id,listing_id').eq('id',conversationId).maybeSingle();
    if(conversationError)throw conversationError;
    if(!conversation)throw new Error("Chat conversation no longer exists.");
    if(conversation.buyer_id!==authUser.id&&conversation.seller_id!==authUser.id)throw new Error("You are not a participant in this chat.");
    const {error}=await sb.from('messages').insert({conversation_id:conversationId,sender_id:authUser.id,body:message});
    if(error)throw error;
    const {error:updateError}=await sb.from('conversations').update({updated_at:new Date().toISOString()}).eq('id',conversationId);
    if(updateError)throw updateError;
    if(conversation.buyer_id===authUser.id&&listing?.id)await sb.from('enquiries').insert({listing_id:listing.id,buyer_id:authUser.id,message});
    e.target.reset();
    await renderChatModal(conversationId,listing,true);
  }catch(err){toast(err.message||"Message could not be sent.",true)}
}
function paymentModal(){let u=user();if(!u){auth("login");return}$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" data-close>×</button><span class="eyebrow">Secure payment</span><h2>Pay for a HarvestHome service</h2><p>Payments are processed by Paystack. Your Paystack secret key stays in the Supabase Edge Function.</p><form id="paymentForm"><label>Email<input name="email" type="email" value="${esc(u.email)}" required></label><label>Service<select name="service"><option value="featured">Featured listing — ₦2,000</option><option value="verification">Seller verification — ₦5,000</option><option value="pro">Professional seller — ₦10,000</option></select></label><button class="primary-btn full">Continue to Paystack</button></form><small class="demo-note">Live payments require the Cloudflare Function, PAYSTACK_SECRET_KEY, and your Paystack account configuration.</small></div></div>`;$('[data-close]')?.addEventListener('click',close);$('#paymentForm')?.addEventListener('submit',paymentSubmit)}
async function paymentSubmit(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const amounts={featured:200000,verification:500000,pro:1000000};if(!sb){toast("Connect Supabase first.",true);return}try{const {data,error}=await sb.functions.invoke('paystack-initialize',{body:{amount:amounts[d.service],service:d.service,currency:'NGN',callback_url:location.origin+'/payment-success.html'}});if(error){let detail=error.message||'Payment initialization failed';try{if(error.context?.json)detail=(await error.context.json()).error||detail}catch{}throw new Error(detail)}if(!data?.authorization_url)throw new Error(data?.error||'Payment service unavailable');location.href=data.authorization_url}catch(err){toast(err.message||'Payment setup is not connected yet.',true)}}
function bind(){
$$("[data-a]").forEach(e=>e.onclick=()=>act(e.dataset.a));$$("[data-scroll]").forEach(e=>e.onclick=()=>document.getElementById(e.dataset.scroll)?.scrollIntoView({behavior:"smooth"}));
$("#countryTop")?.addEventListener("change",e=>switchCountry(e.target.value));$("#profilePhotoInput")?.addEventListener("change",e=>uploadProfilePhoto(e.target.files[0]));$("#countryFilter")?.addEventListener("change",e=>switchCountry(e.target.value));$("#locationFilter")?.addEventListener("change",e=>{state.location=e.target.value;render()});$("#categoryFilter")?.addEventListener("change",e=>{state.category=e.target.value;render()});$("#modeFilter")?.addEventListener("change",e=>{state.mode=e.target.value;render()});
$("#searchInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"){state.search=e.target.value;render()}});$$("[data-cat]").forEach(e=>e.onclick=()=>{state.category=e.dataset.cat;render()});$$("[data-country]").forEach(e=>e.onclick=()=>switchCountry(e.dataset.country));$$("[data-fav]").forEach(e=>e.onclick=x=>{x.stopPropagation();fav(e.dataset.fav)});$$("[data-contact]").forEach(e=>e.onclick=()=>contact(e.dataset.contact));$$("[data-chat]").forEach(e=>e.onclick=async()=>{const l=listings().find(x=>String(x.id)===String(e.dataset.listing));if(l)await openChat(e.dataset.chat,l)});$$("[data-tab]").forEach(e=>e.onclick=()=>{state.dashboardTab=e.dataset.tab;render()});$$("[data-notification]").forEach(e=>e.onclick=()=>markNotificationRead(e.dataset.notification));$$("[data-del]").forEach(e=>e.onclick=()=>del(e.dataset.del));$$("[data-mod]").forEach(e=>e.onclick=()=>moderate(e.dataset.mod))
}
function switchCountry(c){state.country=c;state.location="All locations";state.category="All categories";localStorage.setItem(KEYS.country,c);render()}
async function act(a){if(a==="home"){state.view="marketplace";render();scrollTo(0,0)}if(a==="login")auth("login");if(a==="signup")auth("signup");if(a==="logout"){if(sb) await sb.auth.signOut();localStorage.removeItem(KEYS.session);authUser=null;authProfile=null;state.view="marketplace";render();toast("Logged out.")}if(a==="dashboard"){state.view="dashboard";render()}if(a==="admin"){state.view="dashboard";state.dashboardTab="moderation";render()}if(a==="search"){state.search=$("#searchInput")?.value||"";render()}if(a==="clear"){state.search="";state.location="All locations";state.category="All categories";state.mode="All";render()}if(a==="newListing")listingModal();if(a==="pay")paymentModal();if(a==="markAllNotifications")markAllNotificationsRead()}
function auth(mode){state.authMode=mode;$("#modalRoot").innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" data-close>×</button><span class="eyebrow">${mode==="login"?"Account login":"Join HarvestHome"}</span><h2>${mode==="login"?"Welcome back":"Create your account"}</h2><p>Use your HarvestHome account.</p><form id="authForm">${mode==="signup"?`<label>Full name<input name="name" required></label>`:""}<label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="6" required></label>${mode==="signup"?`<label>Account type<select name="role"><option>Buyer</option><option>Seller</option></select></label>`:""}<button class="primary-btn full"> ${mode==="login"?"Login":"Create account"} </button></form>${mode==="login"?`<button class="link-btn" id="forgot">Forgot password?</button>`:""}<small class="demo-note">Your account is secured by Supabase Auth.</small></div></div>`;bindModal()}
function bindModal(){$("[data-close]")?.addEventListener("click",close);$("#authForm")?.addEventListener("submit",authSubmit);$("#forgot")?.addEventListener("click",showForgot);$("#listingForm")?.addEventListener("submit",listingSubmit)}
function showForgot(){close();$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" data-close>×</button><span class="eyebrow">Account recovery</span><h2>Reset your password</h2><p>Enter your email and Supabase will send a secure password-reset link.</p><form id="forgotForm"><label>Email<input name="email" type="email" required autocomplete="email"></label><button class="primary-btn full">Send reset link</button></form><small class="demo-note">Check your inbox and spam folder. The link returns to HarvestHome.</small></div></div>`;$('[data-close]')?.addEventListener('click',close);$('#forgotForm')?.addEventListener('submit',forgotSubmit)}
async function forgotSubmit(e){e.preventDefault();const email=String(new FormData(e.target).get('email')||'').toLowerCase().trim();if(!sb){toast('Add your Supabase settings in Config.js first.',true);return}try{const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;close();toast('If the account exists, a reset link has been sent.')}catch(err){toast(err.message||'Password reset failed.',true)}}
function showReset(){ $('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="modal-close" data-close>×</button><span class="eyebrow">Password reset</span><h2>Create a new password</h2><form id="resetForm"><label>New password<input name="password" type="password" minlength="8" required autocomplete="new-password"></label><label>Confirm password<input name="confirm" type="password" minlength="8" required autocomplete="new-password"></label><button class="primary-btn full">Update password</button></form></div></div>`;$('[data-close]')?.addEventListener('click',close);$('#resetForm')?.addEventListener('submit',resetSubmit)}
async function resetSubmit(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.password!==d.confirm){toast('Passwords do not match.',true);return}try{const {error}=await sb.auth.updateUser({password:d.password});if(error)throw error;close();history.replaceState({},document.title,location.pathname);toast('Password updated successfully. You can now log in.')}catch(err){toast(err.message||'Reset failed.',true)}}
function close(){$("#modalRoot").innerHTML=""}
async function authSubmit(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(!sb){toast("Add your Supabase URL and anon key in Config.js first.",true);return}try{if(state.authMode==="signup"){const {data,error}=await sb.auth.signUp({email:d.email,password:d.password,options:{data:{full_name:d.name,role:d.role}}});if(error)throw error;close();toast(data.session?"Account created and signed in.":"Account created. Check your email to confirm.");if(data.session){await loadAuth();state.view="dashboard";render();}}else{const {data,error}=await sb.auth.signInWithPassword({email:d.email,password:d.password});if(error)throw error;authUser=data.user;await loadProfile();close();state.view="marketplace";render();toast("Welcome back.")}}catch(err){toast(err.message||"Authentication failed.",true)}}
function listingModal(){if(!user()){auth("login");toast("Log in to create a listing.",true);return}$("#modalRoot").innerHTML=`<div class="modal-backdrop"><div class="modal wide"><button class="modal-close" data-close>×</button><span class="eyebrow">Seller workspace</span><h2>Create international listing</h2><form id="listingForm" class="form-grid"><label>Title<input name="title" required></label><label>Country<select name="country">${options(C.SUPPORTED_COUNTRIES.map(x=>x.name),state.country)}</select></label><label>Category<select name="category">${options(C.CATEGORIES.slice(1),"Houses")}</select></label><label>Location<input name="location" placeholder="City / state / area" required></label><label>Currency<select name="currency">${options(C.SUPPORTED_COUNTRIES.map(x=>x.currency),countryInfo().currency)}</select></label><label>Price<input name="price" type="number" min="0" required></label><label>Type<select name="mode"><option>Sale</option><option>Lease</option></select></label><label class="span-2">Description<textarea name="description" rows="4" required></textarea></label><label class="span-2">Photos (up to ${V5.maxImages})<input name="images" type="file" accept="image/*" multiple></label><label class="span-2">Video (1 file, max ${V5.maxVideoMB} MB)<input name="video" type="file" accept="video/*"></label><button class="primary-btn span-2">Publish listing</button></form><small class="demo-note">Your listing is saved securely in Supabase and stays pending until an Admin or Moderator approves it.</small></div></div>`;bindModal()}
async function listingSubmit(e){e.preventDefault();const fd=new FormData(e.target),d=Object.fromEntries(fd);const images=[...e.target.querySelector('[name=images]').files],video=e.target.querySelector('[name=video]').files[0];if(images.length>C.MAX_IMAGE_FILES){toast(`Please select no more than ${C.MAX_IMAGE_FILES} photos.`,true);return}if(video&&video.size>C.MAX_VIDEO_MB*1024*1024){toast(`Video must be ${C.MAX_VIDEO_MB} MB or smaller.`,true);return}try{if(sb&&authUser){const payload={seller_id:authUser.id,country:d.country,location:d.location,category:d.category,title:d.title,description:d.description,price:Number(d.price),currency:d.currency,mode:d.mode,status:'pending'};const {data:row,error}=await sb.from('listings').insert(payload).select().single();if(error)throw error;let cover_url=null,video_url=null;for(let i=0;i<images.length;i++){const file=images[i],path=`${authUser.id}/${row.id}/images/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('listing-media').upload(path,file,{upsert:false});if(up.error)throw up.error;const pub=sb.storage.from('listing-media').getPublicUrl(path).data.publicUrl;if(i===0)cover_url=pub;await sb.from('listing_media').insert({listing_id:row.id,media_type:'image',storage_path:path});}if(video){const path=`${authUser.id}/${row.id}/video/${Date.now()}-${video.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await sb.storage.from('listing-media').upload(path,video,{upsert:false});if(up.error)throw up.error;video_url=sb.storage.from('listing-media').getPublicUrl(path).data.publicUrl;await sb.from('listing_media').insert({listing_id:row.id,media_type:'video',storage_path:path});}if(cover_url||video_url)await sb.from('listings').update({cover_url,video_url}).eq('id',row.id);await createNotification(authUser.id,'listing_review','Listing submitted for review',`Your listing "${d.title}" has been submitted and is under review. It will appear publicly after a moderator approves it.`,row.id);await syncListings();await syncNotifications();close();state.view='dashboard';state.dashboardTab='listings';render();toast('Listing submitted. It is now under moderator review.');return}if(!sb||!authUser){throw new Error("Seller listing service is unavailable. Please sign in again.")}throw new Error("Your seller listing could not be saved. Please try again.")}catch(err){toast(err.message||'The listing could not be saved.',true)}}
async function moderate(cmd){
 const [action,id]=cmd.split(':');
 if(sb&&authUser){
  try{
   const {data:listing,error:fetchError}=await sb.from('listings').select('id,title,seller_id,status').eq('id',id).maybeSingle();
   if(fetchError)throw fetchError;if(!listing)throw new Error('Listing not found.');
   if(action==='delete'){
    const {error}=await sb.from('listings').update({status:'deleted'}).eq('id',id);if(error)throw error;
    await createNotification(listing.seller_id,'listing_review','Listing removed',`Your listing "${listing.title}" was removed by a moderator.`,listing.id);
   }else{
    const status=action==='approve'?'approved':'rejected';
    const {error}=await sb.from('listings').update({status}).eq('id',id);if(error)throw error;
    if(status==='approved')await createNotification(listing.seller_id,'listing_review','Listing approved',`Your listing "${listing.title}" has been approved and is now visible on HarvestHome.`,listing.id);
    else await createNotification(listing.seller_id,'listing_review','Listing not approved',`Your listing "${listing.title}" was not approved. Please review the listing details and submit an updated listing if needed.`,listing.id);
   }
   await syncListings();toast(action==='delete'?'Listing removed.':`Listing ${action==='approve'?'approved':'rejected'} and seller notified.`);render();return;
  }catch(e){toast(e.message||'Moderation action failed.',true);return}
 }
 let ls=json(KEYS.sellerListings,[]);
 if(action==='delete'){ls=ls.filter(x=>x.id!==id);toast('Listing removed.')}else{let l=ls.find(x=>x.id===id);if(!l)return;l.status=action==='approve'?'approved':'rejected';toast(`Listing ${l.status}.`)}
 put(KEYS.sellerListings,ls);render()
}
async function del(id){
  if(sb&&authUser){
    try{
      const {error}=await sb.from('listings').delete().eq('id',id);
      if(error)throw error;
      await syncListings();
      render();
      toast("Listing deleted.");
      return;
    }catch(err){toast(err.message||"Listing could not be deleted.",true);return}
  }
  put(KEYS.sellerListings,json(KEYS.sellerListings,[]).filter(x=>x.id!==id));
  render();
  toast("Listing deleted.")
}
if(sb){sb.auth.onAuthStateChange(async (event,session)=>{authUser=session?.user||null; if(authUser){await loadProfile();await syncListings();await syncFavourites();await syncNotifications();} else authProfile=null; render(); if(event==='PASSWORD_RECOVERY') setTimeout(showReset,0);}); loadAuth();}else{render();}

})();